In [170]:
import pandas as pd
import numpy as np

In [171]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
data=pd.read_csv('newdata.csv')

In [172]:
data.head()

STATE/UT   DISTRICT  YEAR  MURDER  ATTEMPT TO MURDER  \
0  ANDHRA PRADESH   ADILABAD  2012      81                 80   
1  ANDHRA PRADESH  ANANTAPUR  2012     173                123   
2  ANDHRA PRADESH   CHITTOOR  2012      91                 75   
3  ANDHRA PRADESH   CUDDAPAH  2012     118                 96   
4  ANDHRA PRADESH  CYBERABAD  2012     198                113   

   CULPABLE HOMICIDE NOT AMOUNTING TO MURDER  RAPE  CUSTODIAL RAPE  \
0                                         14    88               0   
1                                          3    18               0   
2                                          5    28               0   
3                                          2    26               0   
4                                         10    75               0   

   OTHER RAPE  KIDNAPPING & ABDUCTION  ...  ARSON  HURT/GREVIOUS HURT  \
0          88                      82  ...     35                2172   
1          18                      74  ...     24                2018   
2          28                      56  ...     27                 622   
3          26                      76  ...      6                2355   
4          75                     158  ...     48                4013   

   DOWRY DEATHS  ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY  \
0             7                                                 90     
1            19                                                195     
2            33                                                 90     
3            13                                                217     
4            45                                                183     

   INSULT TO MODESTY OF WOMEN  CRUELTY BY HUSBAND OR HIS RELATIVES  \
0                         155                                  498   
1                           8                                  130   
2                         269                                  339   
3                          37                                  120   
4                         282                                  976   

   IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES  CAUSING DEATH BY NEGLIGENCE  \
0                                            0                          400   
1                                            0                          576   
2                                            0                          520   
3                                            0                          500   
4                                            0                         1095   

   OTHER IPC CRIMES  TOTAL IPC CRIMES  
0              1079              5710  
1              1043              5441  
2              1398              4465  
3              1360              6110  
4              3155             17979  

[5 rows x 33 columns]

In [173]:
data.tail()

STATE/UT     DISTRICT  YEAR  MURDER  ATTEMPT TO MURDER  \
1629  Lakshadweep  LAKSHADWEEP  2013       0                  0   
1630  Lakshadweep     ZZ TOTAL  2013       0                  0   
1631   Puducherry     KARAIKAL  2013       6                  3   
1632   Puducherry   PUDUCHERRY  2013      25                  8   
1633   Puducherry     ZZ TOTAL  2013      31                 11   

      CULPABLE HOMICIDE NOT AMOUNTING TO MURDER  RAPE  CUSTODIAL RAPE  \
1629                                          0     2               0   
1630                                          0     2               0   
1631                                          0     6               0   
1632                                          2    11               0   
1633                                          2    17               0   

      OTHER RAPE  KIDNAPPING & ABDUCTION  ...  ARSON  HURT/GREVIOUS HURT  \
1629           2                       0  ...      1                   5   
1630           2                       0  ...      1                   5   
1631           6                       3  ...      3                 160   
1632          11                      38  ...     13                 555   
1633          17                      41  ...     16                 715   

      DOWRY DEATHS  ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY  \
1629             0                                                  1     
1630             0                                                  1     
1631             1                                                  1     
1632             0                                                 11     
1633             1                                                 12     

      INSULT TO MODESTY OF WOMEN  CRUELTY BY HUSBAND OR HIS RELATIVES  \
1629                           0                                    0   
1630                           0                                    0   
1631                           1                                    1   
1632                           7                                    7   
1633                           8                                    8   

      IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES  \
1629                                            0   
1630                                            0   
1631                                            0   
1632                                            0   
1633                                            0   

      CAUSING DEATH BY NEGLIGENCE  OTHER IPC CRIMES  TOTAL IPC CRIMES  
1629                            0                18                40  
1630                            0                18                40  
1631                           32               329               643  
1632                          206              1464              3113  
1633                          238              1793              3756  

[5 rows x 33 columns]

In [174]:
data.keys()

Index(['STATE/UT', 'DISTRICT', 'YEAR', 'MURDER', 'ATTEMPT TO MURDER',
       'CULPABLE HOMICIDE NOT AMOUNTING TO MURDER', 'RAPE', 'CUSTODIAL RAPE',
       'OTHER RAPE', 'KIDNAPPING & ABDUCTION',
       'KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS',
       'KIDNAPPING AND ABDUCTION OF OTHERS', 'DACOITY',
       'PREPARATION AND ASSEMBLY FOR DACOITY', 'ROBBERY', 'BURGLARY', 'THEFT',
       'AUTO THEFT', 'OTHER THEFT', 'RIOTS', 'CRIMINAL BREACH OF TRUST',
       'CHEATING', 'COUNTERFIETING', 'ARSON', 'HURT/GREVIOUS HURT',
       'DOWRY DEATHS', 'ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY',
       'INSULT TO MODESTY OF WOMEN', 'CRUELTY BY HUSBAND OR HIS RELATIVES',
       'IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES',
       'CAUSING DEATH BY NEGLIGENCE', 'OTHER IPC CRIMES', 'TOTAL IPC CRIMES'],
      dtype='object')

In [175]:
data.shape

(1634, 33)

In [176]:
data.isnull().sum()

STATE/UT                                               0
DISTRICT                                               0
YEAR                                                   0
MURDER                                                 0
ATTEMPT TO MURDER                                      0
CULPABLE HOMICIDE NOT AMOUNTING TO MURDER              0
RAPE                                                   0
CUSTODIAL RAPE                                         0
OTHER RAPE                                             0
KIDNAPPING & ABDUCTION                                 0
KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS            0
KIDNAPPING AND ABDUCTION OF OTHERS                     0
DACOITY                                                0
PREPARATION AND ASSEMBLY FOR DACOITY                   0
ROBBERY                                                0
BURGLARY                                               0
THEFT                                                  0
AUTO THEFT                     

In [177]:
data['murder and attempt']=data.iloc[:, -30:-27].sum(axis=1)
data.head()

STATE/UT   DISTRICT  YEAR  MURDER  ATTEMPT TO MURDER  \
0  ANDHRA PRADESH   ADILABAD  2012      81                 80   
1  ANDHRA PRADESH  ANANTAPUR  2012     173                123   
2  ANDHRA PRADESH   CHITTOOR  2012      91                 75   
3  ANDHRA PRADESH   CUDDAPAH  2012     118                 96   
4  ANDHRA PRADESH  CYBERABAD  2012     198                113   

   CULPABLE HOMICIDE NOT AMOUNTING TO MURDER  RAPE  CUSTODIAL RAPE  \
0                                         14    88               0   
1                                          3    18               0   
2                                          5    28               0   
3                                          2    26               0   
4                                         10    75               0   

   OTHER RAPE  KIDNAPPING & ABDUCTION  ...  HURT/GREVIOUS HURT  DOWRY DEATHS  \
0          88                      82  ...                2172             7   
1          18                      74  ...                2018            19   
2          28                      56  ...                 622            33   
3          26                      76  ...                2355            13   
4          75                     158  ...                4013            45   

   ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY  \
0                                                 90     
1                                                195     
2                                                 90     
3                                                217     
4                                                183     

   INSULT TO MODESTY OF WOMEN  CRUELTY BY HUSBAND OR HIS RELATIVES  \
0                         155                                  498   
1                           8                                  130   
2                         269                                  339   
3                          37                                  120   
4                         282                                  976   

   IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES  CAUSING DEATH BY NEGLIGENCE  \
0                                            0                          400   
1                                            0                          576   
2                                            0                          520   
3                                            0                          500   
4                                            0                         1095   

   OTHER IPC CRIMES  TOTAL IPC CRIMES  murder and attempt  
0              1079              5710                 175  
1              1043              5441                 299  
2              1398              4465                 171  
3              1360              6110                 216  
4              3155             17979                 321  

[5 rows x 34 columns]

In [178]:
data['Rape']=data.iloc[:, -28:-25].sum(axis=1)
data.head()

STATE/UT   DISTRICT  YEAR  MURDER  ATTEMPT TO MURDER  \
0  ANDHRA PRADESH   ADILABAD  2012      81                 80   
1  ANDHRA PRADESH  ANANTAPUR  2012     173                123   
2  ANDHRA PRADESH   CHITTOOR  2012      91                 75   
3  ANDHRA PRADESH   CUDDAPAH  2012     118                 96   
4  ANDHRA PRADESH  CYBERABAD  2012     198                113   

   CULPABLE HOMICIDE NOT AMOUNTING TO MURDER  RAPE  CUSTODIAL RAPE  \
0                                         14    88               0   
1                                          3    18               0   
2                                          5    28               0   
3                                          2    26               0   
4                                         10    75               0   

   OTHER RAPE  KIDNAPPING & ABDUCTION  ...  DOWRY DEATHS  \
0          88                      82  ...             7   
1          18                      74  ...            19   
2          28                      56  ...            33   
3          26                      76  ...            13   
4          75                     158  ...            45   

   ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY  \
0                                                 90     
1                                                195     
2                                                 90     
3                                                217     
4                                                183     

   INSULT TO MODESTY OF WOMEN  CRUELTY BY HUSBAND OR HIS RELATIVES  \
0                         155                                  498   
1                           8                                  130   
2                         269                                  339   
3                          37                                  120   
4                         282                                  976   

   IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES  CAUSING DEATH BY NEGLIGENCE  \
0                                            0                          400   
1                                            0                          576   
2                                            0                          520   
3                                            0                          500   
4                                            0                         1095   

   OTHER IPC CRIMES  TOTAL IPC CRIMES  murder and attempt  Rape  
0              1079              5710                 175   176  
1              1043              5441                 299    36  
2              1398              4465                 171    56  
3              1360              6110                 216    52  
4              3155             17979                 321   150  

[5 rows x 35 columns]

In [179]:
data.drop(data.columns[[3,4,5,6,7,8]], axis=1, inplace = True)
data.head()

STATE/UT   DISTRICT  YEAR  KIDNAPPING & ABDUCTION  \
0  ANDHRA PRADESH   ADILABAD  2012                      82   
1  ANDHRA PRADESH  ANANTAPUR  2012                      74   
2  ANDHRA PRADESH   CHITTOOR  2012                      56   
3  ANDHRA PRADESH   CUDDAPAH  2012                      76   
4  ANDHRA PRADESH  CYBERABAD  2012                     158   

   KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS  \
0                                           61   
1                                           63   
2                                           49   
3                                           44   
4                                          102   

   KIDNAPPING AND ABDUCTION OF OTHERS  DACOITY  \
0                                  21        2   
1                                  11       14   
2                                   7        3   
3                                  32        4   
4                                  56       14   

   PREPARATION AND ASSEMBLY FOR DACOITY  ROBBERY  BURGLARY  ...  DOWRY DEATHS  \
0                                     0       14       240  ...             7   
1                                     1        6       211  ...            19   
2                                     0       10       136  ...            33   
3                                     0        9       136  ...            13   
4                                     0       86      1101  ...            45   

   ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY  \
0                                                 90     
1                                                195     
2                                                 90     
3                                                217     
4                                                183     

   INSULT TO MODESTY OF WOMEN  CRUELTY BY HUSBAND OR HIS RELATIVES  \
0                         155                                  498   
1                           8                                  130   
2                         269                                  339   
3                          37                                  120   
4                         282                                  976   

   IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES  CAUSING DEATH BY NEGLIGENCE  \
0                                            0                          400   
1                                            0                          576   
2                                            0                          520   
3                                            0                          500   
4                                            0                         1095   

   OTHER IPC CRIMES  TOTAL IPC CRIMES  murder and attempt  Rape  
0              1079              5710                 175   176  
1              1043              5441                 299    36  
2              1398              4465                 171    56  
3              1360              6110                 216    52  
4              3155             17979                 321   150  

[5 rows x 29 columns]

In [180]:
data['Kidnapping and Abduction']=data.iloc[:, -26:-23].sum(axis=1)
data.head()

STATE/UT   DISTRICT  YEAR  KIDNAPPING & ABDUCTION  \
0  ANDHRA PRADESH   ADILABAD  2012                      82   
1  ANDHRA PRADESH  ANANTAPUR  2012                      74   
2  ANDHRA PRADESH   CHITTOOR  2012                      56   
3  ANDHRA PRADESH   CUDDAPAH  2012                      76   
4  ANDHRA PRADESH  CYBERABAD  2012                     158   

   KIDNAPPING AND ABDUCTION OF WOMEN AND GIRLS  \
0                                           61   
1                                           63   
2                                           49   
3                                           44   
4                                          102   

   KIDNAPPING AND ABDUCTION OF OTHERS  DACOITY  \
0                                  21        2   
1                                  11       14   
2                                   7        3   
3                                  32        4   
4                                  56       14   

   PREPARATION AND ASSEMBLY FOR DACOITY  ROBBERY  BURGLARY  ...  \
0                                     0       14       240  ...   
1                                     1        6       211  ...   
2                                     0       10       136  ...   
3                                     0        9       136  ...   
4                                     0       86      1101  ...   

   ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY  \
0                                                 90     
1                                                195     
2                                                 90     
3                                                217     
4                                                183     

   INSULT TO MODESTY OF WOMEN  CRUELTY BY HUSBAND OR HIS RELATIVES  \
0                         155                                  498   
1                           8                                  130   
2                         269                                  339   
3                          37                                  120   
4                         282                                  976   

   IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES  CAUSING DEATH BY NEGLIGENCE  \
0                                            0                          400   
1                                            0                          576   
2                                            0                          520   
3                                            0                          500   
4                                            0                         1095   

   OTHER IPC CRIMES  TOTAL IPC CRIMES  murder and attempt  Rape  \
0              1079              5710                 175   176   
1              1043              5441                 299    36   
2              1398              4465                 171    56   
3              1360              6110                 216    52   
4              3155             17979                 321   150   

   Kidnapping and Abduction  
0                       164  
1                       148  
2                       112  
3                       152  
4                       316  

[5 rows x 30 columns]

In [181]:
data.drop(data.columns[[3,4,5]], axis = 1, inplace = True)
data.head()

STATE/UT   DISTRICT  YEAR  DACOITY  \
0  ANDHRA PRADESH   ADILABAD  2012        2   
1  ANDHRA PRADESH  ANANTAPUR  2012       14   
2  ANDHRA PRADESH   CHITTOOR  2012        3   
3  ANDHRA PRADESH   CUDDAPAH  2012        4   
4  ANDHRA PRADESH  CYBERABAD  2012       14   

   PREPARATION AND ASSEMBLY FOR DACOITY  ROBBERY  BURGLARY  THEFT  AUTO THEFT  \
0                                     0       14       240    373         104   
1                                     1        6       211    581         155   
2                                     0       10       136    501         208   
3                                     0        9       136    513         154   
4                                     0       86      1101   4461        1887   

   OTHER THEFT  ...  ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY  \
0          269  ...                                                 90     
1          426  ...                                                195     
2          293  ...                                                 90     
3          359  ...                                                217     
4         2574  ...                                                183     

   INSULT TO MODESTY OF WOMEN  CRUELTY BY HUSBAND OR HIS RELATIVES  \
0                         155                                  498   
1                           8                                  130   
2                         269                                  339   
3                          37                                  120   
4                         282                                  976   

   IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES  CAUSING DEATH BY NEGLIGENCE  \
0                                            0                          400   
1                                            0                          576   
2                                            0                          520   
3                                            0                          500   
4                                            0                         1095   

   OTHER IPC CRIMES  TOTAL IPC CRIMES  murder and attempt  Rape  \
0              1079              5710                 175   176   
1              1043              5441                 299    36   
2              1398              4465                 171    56   
3              1360              6110                 216    52   
4              3155             17979                 321   150   

   Kidnapping and Abduction  
0                       164  
1                       148  
2                       112  
3                       152  
4                       316  

[5 rows x 27 columns]

In [182]:
data.drop(data.columns[[4,10,11,12,13,14]], axis = 1, inplace = True)
data.head()

STATE/UT   DISTRICT  YEAR  DACOITY  ROBBERY  BURGLARY  THEFT  \
0  ANDHRA PRADESH   ADILABAD  2012        2       14       240    373   
1  ANDHRA PRADESH  ANANTAPUR  2012       14        6       211    581   
2  ANDHRA PRADESH   CHITTOOR  2012        3       10       136    501   
3  ANDHRA PRADESH   CUDDAPAH  2012        4        9       136    513   
4  ANDHRA PRADESH  CYBERABAD  2012       14       86      1101   4461   

   AUTO THEFT  OTHER THEFT  HURT/GREVIOUS HURT  ...  \
0         104          269                2172  ...   
1         155          426                2018  ...   
2         208          293                 622  ...   
3         154          359                2355  ...   
4        1887         2574                4013  ...   

   ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY  \
0                                                 90     
1                                                195     
2                                                 90     
3                                                217     
4                                                183     

   INSULT TO MODESTY OF WOMEN  CRUELTY BY HUSBAND OR HIS RELATIVES  \
0                         155                                  498   
1                           8                                  130   
2                         269                                  339   
3                          37                                  120   
4                         282                                  976   

   IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES  CAUSING DEATH BY NEGLIGENCE  \
0                                            0                          400   
1                                            0                          576   
2                                            0                          520   
3                                            0                          500   
4                                            0                         1095   

   OTHER IPC CRIMES  TOTAL IPC CRIMES  murder and attempt  Rape  \
0              1079              5710                 175   176   
1              1043              5441                 299    36   
2              1398              4465                 171    56   
3              1360              6110                 216    52   
4              3155             17979                 321   150   

   Kidnapping and Abduction  
0                       164  
1                       148  
2                       112  
3                       152  
4                       316  

[5 rows x 21 columns]

In [183]:
data['Dacoity and various theft']=data.iloc[:, -18:-12].sum(axis=1)
data.head()

STATE/UT   DISTRICT  YEAR  DACOITY  ROBBERY  BURGLARY  THEFT  \
0  ANDHRA PRADESH   ADILABAD  2012        2       14       240    373   
1  ANDHRA PRADESH  ANANTAPUR  2012       14        6       211    581   
2  ANDHRA PRADESH   CHITTOOR  2012        3       10       136    501   
3  ANDHRA PRADESH   CUDDAPAH  2012        4        9       136    513   
4  ANDHRA PRADESH  CYBERABAD  2012       14       86      1101   4461   

   AUTO THEFT  OTHER THEFT  HURT/GREVIOUS HURT  ...  \
0         104          269                2172  ...   
1         155          426                2018  ...   
2         208          293                 622  ...   
3         154          359                2355  ...   
4        1887         2574                4013  ...   

   INSULT TO MODESTY OF WOMEN  CRUELTY BY HUSBAND OR HIS RELATIVES  \
0                         155                                  498   
1                           8                                  130   
2                         269                                  339   
3                          37                                  120   
4                         282                                  976   

   IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES  CAUSING DEATH BY NEGLIGENCE  \
0                                            0                          400   
1                                            0                          576   
2                                            0                          520   
3                                            0                          500   
4                                            0                         1095   

   OTHER IPC CRIMES  TOTAL IPC CRIMES  murder and attempt  Rape  \
0              1079              5710                 175   176   
1              1043              5441                 299    36   
2              1398              4465                 171    56   
3              1360              6110                 216    52   
4              3155             17979                 321   150   

   Kidnapping and Abduction  Dacoity and various theft  
0                       164                       1002  
1                       148                       1393  
2                       112                       1151  
3                       152                       1175  
4                       316                      10123  

[5 rows x 22 columns]

In [184]:
data.drop(data.columns[[3,4,5,6,7,8]], axis = 1, inplace = True)
data.head()

STATE/UT   DISTRICT  YEAR  HURT/GREVIOUS HURT  DOWRY DEATHS  \
0  ANDHRA PRADESH   ADILABAD  2012                2172             7   
1  ANDHRA PRADESH  ANANTAPUR  2012                2018            19   
2  ANDHRA PRADESH   CHITTOOR  2012                 622            33   
3  ANDHRA PRADESH   CUDDAPAH  2012                2355            13   
4  ANDHRA PRADESH  CYBERABAD  2012                4013            45   

   ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY  \
0                                                 90     
1                                                195     
2                                                 90     
3                                                217     
4                                                183     

   INSULT TO MODESTY OF WOMEN  CRUELTY BY HUSBAND OR HIS RELATIVES  \
0                         155                                  498   
1                           8                                  130   
2                         269                                  339   
3                          37                                  120   
4                         282                                  976   

   IMPORTATION OF GIRLS FROM FOREIGN COUNTRIES  CAUSING DEATH BY NEGLIGENCE  \
0                                            0                          400   
1                                            0                          576   
2                                            0                          520   
3                                            0                          500   
4                                            0                         1095   

   OTHER IPC CRIMES  TOTAL IPC CRIMES  murder and attempt  Rape  \
0              1079              5710                 175   176   
1              1043              5441                 299    36   
2              1398              4465                 171    56   
3              1360              6110                 216    52   
4              3155             17979                 321   150   

   Kidnapping and Abduction  Dacoity and various theft  
0                       164                       1002  
1                       148                       1393  
2                       112                       1151  
3                       152                       1175  
4                       316                      10123

In [185]:
data.drop(data.columns[[3,7,8,10,11]], axis = 1, inplace = True)
data.head()

STATE/UT   DISTRICT  YEAR  DOWRY DEATHS  \
0  ANDHRA PRADESH   ADILABAD  2012             7   
1  ANDHRA PRADESH  ANANTAPUR  2012            19   
2  ANDHRA PRADESH   CHITTOOR  2012            33   
3  ANDHRA PRADESH   CUDDAPAH  2012            13   
4  ANDHRA PRADESH  CYBERABAD  2012            45   

   ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY  \
0                                                 90     
1                                                195     
2                                                 90     
3                                                217     
4                                                183     

   INSULT TO MODESTY OF WOMEN  CAUSING DEATH BY NEGLIGENCE  \
0                         155                          400   
1                           8                          576   
2                         269                          520   
3                          37                          500   
4                         282                         1095   

   murder and attempt  Rape  Kidnapping and Abduction  \
0                 175   176                       164   
1                 299    36                       148   
2                 171    56                       112   
3                 216    52                       152   
4                 321   150                       316   

   Dacoity and various theft  
0                       1002  
1                       1393  
2                       1151  
3                       1175  
4                      10123

In [186]:
data['violence against women']=data.iloc[:, -8:-5].sum(axis=1)
data.head()

STATE/UT   DISTRICT  YEAR  DOWRY DEATHS  \
0  ANDHRA PRADESH   ADILABAD  2012             7   
1  ANDHRA PRADESH  ANANTAPUR  2012            19   
2  ANDHRA PRADESH   CHITTOOR  2012            33   
3  ANDHRA PRADESH   CUDDAPAH  2012            13   
4  ANDHRA PRADESH  CYBERABAD  2012            45   

   ASSAULT ON WOMEN WITH INTENT TO OUTRAGE HER MODESTY  \
0                                                 90     
1                                                195     
2                                                 90     
3                                                217     
4                                                183     

   INSULT TO MODESTY OF WOMEN  CAUSING DEATH BY NEGLIGENCE  \
0                         155                          400   
1                           8                          576   
2                         269                          520   
3                          37                          500   
4                         282                         1095   

   murder and attempt  Rape  Kidnapping and Abduction  \
0                 175   176                       164   
1                 299    36                       148   
2                 171    56                       112   
3                 216    52                       152   
4                 321   150                       316   

   Dacoity and various theft  violence against women  
0                       1002                     252  
1                       1393                     222  
2                       1151                     392  
3                       1175                     267  
4                      10123                     510

In [187]:
data.drop(data.columns[[3,4,5]], axis = 1, inplace = True)
data.head()

STATE/UT   DISTRICT  YEAR  CAUSING DEATH BY NEGLIGENCE  \
0  ANDHRA PRADESH   ADILABAD  2012                          400   
1  ANDHRA PRADESH  ANANTAPUR  2012                          576   
2  ANDHRA PRADESH   CHITTOOR  2012                          520   
3  ANDHRA PRADESH   CUDDAPAH  2012                          500   
4  ANDHRA PRADESH  CYBERABAD  2012                         1095   

   murder and attempt  Rape  Kidnapping and Abduction  \
0                 175   176                       164   
1                 299    36                       148   
2                 171    56                       112   
3                 216    52                       152   
4                 321   150                       316   

   Dacoity and various theft  violence against women  
0                       1002                     252  
1                       1393                     222  
2                       1151                     392  
3                       1175                     267  
4                      10123                     510

In [188]:
data.drop(data.columns[[3]], axis=1, inplace = True)
data.head()

STATE/UT   DISTRICT  YEAR  murder and attempt  Rape  \
0  ANDHRA PRADESH   ADILABAD  2012                 175   176   
1  ANDHRA PRADESH  ANANTAPUR  2012                 299    36   
2  ANDHRA PRADESH   CHITTOOR  2012                 171    56   
3  ANDHRA PRADESH   CUDDAPAH  2012                 216    52   
4  ANDHRA PRADESH  CYBERABAD  2012                 321   150   

   Kidnapping and Abduction  Dacoity and various theft  violence against women  
0                       164                       1002                     252  
1                       148                       1393                     222  
2                       112                       1151                     392  
3                       152                       1175                     267  
4                       316                      10123                     510

In [189]:
data.rename(columns = {'STATE/UT':'STATE'}, inplace = True)
data.head()

STATE   DISTRICT  YEAR  murder and attempt  Rape  \
0  ANDHRA PRADESH   ADILABAD  2012                 175   176   
1  ANDHRA PRADESH  ANANTAPUR  2012                 299    36   
2  ANDHRA PRADESH   CHITTOOR  2012                 171    56   
3  ANDHRA PRADESH   CUDDAPAH  2012                 216    52   
4  ANDHRA PRADESH  CYBERABAD  2012                 321   150   

   Kidnapping and Abduction  Dacoity and various theft  violence against women  
0                       164                       1002                     252  
1                       148                       1393                     222  
2                       112                       1151                     392  
3                       152                       1175                     267  
4                       316                      10123                     510

In [311]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
data['STATE'] = le.fit_transform(data['STATE'])
data['DISTRICT'] = le.fit_transform(data['DISTRICT'])

data.head()

STATE  DISTRICT  YEAR  murder and attempt  Rape  Kidnapping and Abduction  \
0      2         2  2012                 175   176                       164   
1      2        28  2012                 299    36                       148   
2      2       147  2012                 171    56                       112   
3      2       164  2012                 216    52                       152   
4      2       166  2012                 321   150                       316   

   Dacoity and various theft  violence against women  
0                       1002                     252  
1                       1393                     222  
2                       1151                     392  
3                       1175                     267  
4                      10123                     510

In [312]:
X = data.iloc[:,[0,1,2]].values
X

array([[   2,    2, 2012],
       [   2,   28, 2012],
       [   2,  147, 2012],
       ...,
       [  54,  369, 2013],
       [  54,  566, 2013],
       [  54,  780, 2013]], dtype=int64)

In [313]:
Y = data.iloc[:,[3,4,5,6,7]].values
Y

array([[ 175,  176,  164, 1002,  252],
       [ 299,   36,  148, 1393,  222],
       [ 171,   56,  112, 1151,  392],
       ...,
       [   9,   12,    6,  133,    3],
       [  35,   22,   76, 1137,   18],
       [  44,   34,   82, 1270,   21]], dtype=int64)

In [314]:
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_multilabel_classification

In [315]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.20, random_state=1)

In [316]:
X.shape
Y.shape
print(X.shape,Y.shape)

(1634, 3) (1634, 5)


In [317]:
X_train.shape
Y_train.shape
X_test.shape
Y_test.shape

(327, 5)

In [318]:
for i in range(10):
	print(X[i], Y[i])

[   2    2 2012] [ 175  176  164 1002  252]
[   2   28 2012] [ 299   36  148 1393  222]
[   2  147 2012] [ 171   56  112 1151  392]
[   2  164 2012] [ 216   52  152 1175  267]
[   2  166 2012] [  321   150   316 10123   510]
[   2  214 2012] [ 167  142  108 2084  425]
[   2  268 2012] [  7   2   2 540   3]
[   2  269 2012] [ 165   46  126 1568  356]
[   2  270 2012] [ 112   48   84 1994  176]
[   2  297 2012] [ 274  148  176 8104  309]


In [319]:
#KNN classification
from sklearn.multioutput import MultiOutputClassifier
from sklearn.neighbors import KNeighborsClassifier
knn= KNeighborsClassifier()
classifier= MultiOutputClassifier(knn,n_jobs=-1)
classifier.fit(X_train,Y_train)
pred= classifier.predict(X_test)
pred

array([[  42,   40,   30,  527,   27],
       [   6,    2,    4,  128,    3],
       [  15,   10,   80,  621,   21],
       ...,
       [  15,    2,    8,  588,    5],
       [  44,   28,   30, 1329,   43],
       [   1,    2,    8,   25,    1]], dtype=int64)

In [320]:
acc_list = []
for i in range(Y_test.shape[0]):
        set_true = set( np.where(Y_train[i])[0] )
        set_pred = set( np.where(pred[i])[0] )
        tmp_a = None
        if len(set_true) == 0 and len(set_pred) == 0:
            tmp_a = 1
        else:
            tmp_a = len(set_true.intersection(set_pred))/\
                    float( len(set_true.union(set_pred)) )
        acc_list.append(tmp_a)

In [321]:
print ('score', np.mean(acc_list))

score 0.858868501529052


In [322]:
testdata=[[45,3,2016]]

In [323]:
classifier.predict(testdata)

array([[ 17,  38,   4, 774,  37]], dtype=int64)

In [324]:
#Decision tree classifier
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier()
class1=MultiOutputClassifier(dtc)
class1.fit(X_train,Y_train)
pred1=class1.predict(X_test)
pred1

array([[ 118,   90,  282, 1172,   52],
       [  31,   28,   40,  128,    3],
       [  84,  124,  148, 1252,   54],
       ...,
       [  88,   30,  136,  362,   72],
       [ 125,  156, 1020, 5351,  103],
       [ 205,   48,   70,  507,   80]], dtype=int64)

In [325]:
acc_list = []
for i in range(Y_test.shape[0]):
        set_true = set( np.where(Y_train[i])[0] )
        set_pred = set( np.where(pred1[i])[0] )
        tmp_a = None
        if len(set_true) == 0 and len(set_pred) == 0:
            tmp_a = 1
        else:
            tmp_a = len(set_true.intersection(set_pred))/\
                    float( len(set_true.union(set_pred)) )
        acc_list.append(tmp_a)

In [326]:
print ('score', np.mean(acc_list)*100)

score 94.06727828746178


In [327]:
testdata=[[54,780,2018]]

In [328]:
class1.predict(testdata)

array([[  44,   34,   82, 1270,   21]], dtype=int64)

In [329]:
#random forest classifier
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier()
class2=MultiOutputClassifier(rfc)
class2.fit(X_train,Y_train)
pred2=class2.predict(X_test)
pred2

array([[  76,   40,  130, 1172,   52],
       [  31,   28,   40,  128,    3],
       [  84,  124,  208, 1252,   99],
       ...,
       [  88,   30,  136,  362,   72],
       [ 125,  156, 1020, 5351,  103],
       [ 205,  458,  278,  507,  358]], dtype=int64)

In [330]:
acc_list = []
for i in range(Y_test.shape[0]):
        set_true = set( np.where(Y_train[i])[0] )
        set_pred = set( np.where(pred2[i])[0] )
        tmp_a = None
        if len(set_true) == 0 and len(set_pred) == 0:
            tmp_a = 1
        else:
            tmp_a = len(set_true.intersection(set_pred))/\
                    float( len(set_true.union(set_pred)) )
        acc_list.append(tmp_a)

In [331]:
print ('score', np.mean(acc_list)*100)

score 92.5993883792049


In [156]:
testdata=[[45,3,2016]]

In [157]:
class2.predict(testdata)

array([[ 189,  210,  162, 4153,  287]], dtype=int64)

In [158]:
import pickle

In [162]:
file=open('crime_model.pkl','wb')
pickle.dump(class2,file)